### ISSUE TITLE
login not work

### ISSUE THREAD

**Issue by Gumxball** [notN1CHO/AresHost-OGP#1]
![Screenshot_2023-03-29-16-57-21-018-edit_com discord](https://user-images.githubusercontent.com/121202906/228692250-e5d09211-fd62-47e6-8260-c8f8d5c0e83b.jpg)
I put the ip in config.js But when I log into my account, it does not work

**Comment by notN1CHO** [comment]
Hey, You should put your OGP account informations on the command.

**Comment by Gumxball** [comment]
> 

I put it and this is strange in an order

**Comment by notN1CHO** [comment]
you get the same error?

**Comment by Gumxball** [comment]
yeah

**Comment by notN1CHO** [comment]
can you send a screenshot what console said?

**Comment by notN1CHO** [comment]
> ![Screenshot_2023-03-30-00-15-40-279-edit_com android chrome](https://user-images.githubusercontent.com/121202906/228917533-563fa278-6c39-403d-8c2a-653787c5467c.jpg)

Oh, you should remove "/" in serverip, go to config.js, open it and go to serverip and edit it to be like that :

serverip: "http://51.38.1...",

**Comment by notN1CHO** [comment]
problem solved?

**Comment by Gumxball** [comment]
Thanks
